<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="sharework_cell_macro" >

<xacro:macro name="sharework_cell" params="
  zed_camera_name:='zed'
  zed_camera_model:='zed2'
  fake_cameras:=true
  fake_robot:=true
  fake_gripper:=true
  robot_parent_link:='cursor'
  robot_origin_x:='0.0'
  robot_origin_y:='0.0'
  robot_origin_z:='0.0'
  robot_origin_roll:='${pi}'
  robot_origin_pitch:='0.0'
  robot_origin_yaw:='0.0'
  ur_type:='ur10e'
  robot_name:='$(arg ur_type)'
  robot_tf_prefix:='$(arg ur_type)'
  joint_limits_parameters_file:='$(find sharework_cembre_description)/config/joint_limits.yaml'
  kinematics_parameters_file:='$(find sharework_cembre_description)/config/cembre_ur10e.yaml'
  physical_parameters_file:='$(find ur_description)/config/$(arg ur_type)/physical_parameters.yaml'
  visual_parameters_file:='$(find ur_description)/config/$(arg ur_type)/visual_parameters.yaml'
  safety_limits:='false'
  safety_pos_margin:=0.15
  safety_k_position:=20
  generate_ros2_control_tag:=true
  transmission_hw_interface:=hardware_interface/PositionJointInterface
  fake_sensor_commands:=false
  sim_gazebo:=false
  sim_ignition:=false
  headless_mode:=false
  initial_positions:=${dict(
                        shoulder_pan_joint=0.0,
                        shoulder_lift_joint=-1.57,
                        elbow_joint=0.0,
                        wrist_1_joint=-1.57,
                        wrist_2_joint=0.0,
                        wrist_3_joint=0.0,
                        left_knuckle_joint=0.0
                      )}
  use_tool_communication:=false
  tool_voltage:=0
  tool_parity:=0
  tool_baud_rate:=115200
  tool_stop_bits:=1
  tool_rx_idle_chars:=1.5
  tool_tx_idle_chars:=3.5
  tool_device_name:=/tmp/ttyUR
  tool_tcp_port:=54321
  robot_ip:=192.168.1.102
  script_filename:=to_be_filled_by_ur_robot_driver
  output_recipe_filename:=to_be_filled_by_ur_robot_driver
  input_recipe_filename:=to_be_filled_by_ur_robot_driver
  reverse_port:=50001
  script_sender_port:=50002
  reverse_ip:=0.0.0.0
  script_command_port:=50004
  trajectory_port:=50003
  non_blocking_read:=true
  keep_alive_count:=2
  robotiq_sim_isaac:=false
  robotiq_isaac_joint_commands:=/isaac_joint_commands
  robotiq_isaac_joint_states:=/isaac_joint_states
  robotiq_mock_sensor_commands:=false
  robotiq_include_ros2_control:=true
  robotiq_use_socket_communication:=false
  robotiq_ip_address:=192.168.10.2
  robotiq_port:=63352
  robotiq_connection_timeout:=30000
  robotiq_activate_gripper_by_default:=1">
  
<!-- ZED camera args-->
<xacro:property name="custom_baseline"  value="0.0" />
<!-- If GNSS fusion is enabled the position of the antenna with respect to the camera mount point is required -->
<xacro:property name="enable_gnss"      value="false" />
<xacro:property name="gnss_x"           value="0.0" />
<xacro:property name="gnss_y"           value="0.0" />
<xacro:property name="gnss_z"           value="0.0" />


<!-- Geometric properties -->
<xacro:property name="column_size_x" value="0.580" />
<xacro:property name="column_size_y" value="0.120" />
<xacro:property name="column_size_z" value="3.000" />

<xacro:property name="table_height" value="0.895" />
<xacro:property name="table_size_x" value="0.600" />
<xacro:property name="table_size_y" value="2.000" />
<xacro:property name="table_size_z" value="0.040" />

<xacro:property name="beam_size_x" value="${column_size_x}" />
<xacro:property name="beam_size_y" value="${table_size_y}" />
<xacro:property name="beam_size_z" value="${column_size_y}" />

<xacro:property name="rail_size_x" value="0.36" />
<xacro:property name="rail_size_y" value="3.224" />
<xacro:property name="rail_size_z" value="0.12" />
<xacro:property name="rail_distance" value="${0.12+0.5*rail_size_x}" />

<xacro:property name="upper_beam_height" value="2.208" />

<xacro:property name="guide_offset" value="${0.70-0.205}" />

<xacro:property name="cursor_size" value="0.280" />
<xacro:property name="guide_size_x" value="${cursor_size}" />
<xacro:property name="guide_size_y" value="${beam_size_y}" />
<xacro:property name="guide_size_z" value="0.14" />
<xacro:property name="guide_distance_x" value="0.185" />
<xacro:property name="anti_crushing_distance" value="0.040" />

<xacro:property name="guide_distance_y" value="${0.385+0.041}" />

<xacro:property name="wall_size_x" value="0.1" />
<xacro:property name="wall_size_y" value="${2+table_size_y+2*column_size_y}" />
<xacro:property name="wall_size_z" value="${column_size_z}" />
<xacro:property name="wall_distance" value="0.40" />

<xacro:property name="floor_size_x" value="6" />
<xacro:property name="floor_size_y" value="6" />
<xacro:property name="floor_size_z" value="0.01" />

<xacro:property name="virtual_wall_width" value="0.001" />
<xacro:property name="virtual_wall2_gap" value="1.10" />

<!-- electric plug cabinet -->
<xacro:property name="ec_size_x" value="0.40" />
<xacro:property name="ec_size_y" value="0.70" />
<xacro:property name="ec_size_z" value="2.00" />

<xacro:property name="grey" value="0.517647058823529	0.529411764705882	0.537254901960784 1" />
<xacro:property name="beech" value="0.952941176470588	0.694117647058823	0.392156862745098 1" />


  <xacro:include filename="$(find sharework_cembre_description)/urdf/sharework_fixed_parts.xacro" />
  <xacro:sharework_fixed_parts />

  <xacro:include filename="$(find sharework_cembre_description)/urdf/sharework_sensors.xacro"/>
  <xacro:sharework_sensors
          fake_cameras="${fake_cameras}"
  />



  <!-- ur10e + robotiq gripper -->
<xacro:include filename="$(find ur_robotiq_description)/urdf/ur_robotiq.xacro"/>
<xacro:ur_robotiq
        fake_ur="${fake_robot}"
  fake_gripper="${fake_gripper}"
  parent_link="${robot_parent_link}"
  origin_x="${robot_origin_x}"
  origin_y="${robot_origin_y}"
  origin_z="${robot_origin_z}"
  origin_roll="${robot_origin_roll}"
  origin_pitch="${robot_origin_pitch}"
  origin_yaw="${robot_origin_yaw}"
  ur_type="${ur_type}"
  robot_name="${robot_name}"
  tf_prefix="${robot_tf_prefix}"
  joint_limits_parameters_file="${joint_limit_params}"
  kinematics_parameters_file="${kinematics_params}"
  physical_parameters_file="${physical_params}"
  visual_parameters_file="${visual_params}"
  safety_limits="${safety_limits}"
  safety_pos_margin="${safety_pos_margin}"
  safety_k_position="${safety_k_position}"
  generate_ros2_control_tag="${generate_ros2_control_tag}"
  transmission_hw_interface="${transmission_hw_interface}"
  fake_sensor_commands="${fake_sensor_commands}"
  sim_gazebo="${sim_gazebo}"
  sim_ignition="${sim_ignition}"
  headless_mode="${headless_mode}"
  initial_positions="${initial_positions}"
  use_tool_communication="${use_tool_communication}"
  tool_voltage="${tool_voltage}"
  tool_parity="${tool_parity}"
  tool_baud_rate="${tool_baud_rate}"
  tool_stop_bits="${tool_stop_bits}"
  tool_rx_idle_chars="${tool_rx_idle_chars}"
  tool_tx_idle_chars="${tool_tx_idle_chars}"
  tool_device_name="${tool_device_name}"
  tool_tcp_port="${tool_tcp_port}"
  robot_ip="${robot_ip}"
  script_filename="${script_filename}"
  output_recipe_filename="${output_recipe_filename}"
  input_recipe_filename="${input_recipe_filename}"
  reverse_port="${reverse_port}"
  script_sender_port="${script_sender_port}"
  reverse_ip="${reverse_ip}"
  script_command_port="${script_command_port}"
  trajectory_port="${trajectory_port}"
  non_blocking_read="${non_blocking_read}"
  keep_alive_count="${keep_alive_count}"
  robotiq_sim_ignition="${sim_ignition}"
  robotiq_sim_isaac="${robotiq_sim_isaac}"
  robotiq_isaac_joint_commands="${robotiq_isaac_joint_commands}"
  robotiq_isaac_joint_states="${robotiq_isaac_joint_states}"
  robotiq_mock_sensor_commands="${robotiq_mock_sensor_commands}"
  robotiq_include_ros2_control="${robotiq_include_ros2_control}"
  robotiq_use_socket_communication="${robotiq_use_socket_communication}"
  robotiq_ip_address="${robotiq_ip_address}"
  robotiq_port="${robotiq_port}"
  robotiq_connection_timeout="${robotiq_connection_timeout}"
  robotiq_activate_gripper_by_default="${robotiq_activate_gripper_by_default}"/>


</xacro:macro>

</robot>
