inbound:
  objects:
  - {type: "squadra_piccola",  frame: "table", position: [ 0.005, 1.005, 0.001], quaternion: [0,0,0,1], inbound: "sp1"}
  - {type: "squadra_piccola",  frame: "table", position: [ 0.005, 1.078, 0.001], quaternion: [0,0,0,1], inbound: "sp2"}
  - {type: "squadra_piccola",  frame: "table", position: [ 0.005, 1.136, 0.001], quaternion: [0,0,0,1], inbound: "sp3"}
  - {type: "squadra_piccola",  frame: "table", position: [ 0.005, 1.208, 0.001], quaternion: [0,0,0,1], inbound: "sp4"}
  - {type: "squadra_piccola",  frame: "table", position: [ 0.005, 1.268, 0.001], quaternion: [0,0,0,1], inbound: "sp5"}

  - {type: "squadra_grande",  frame: "table", position: [ 0.061, 0.529, 0.001], quaternion: [ 0, 0, -0.7071068, 0.7071068 ], inbound: "sg1"}
  - {type: "squadra_grande",  frame: "table", position: [ 0.061, 0.673, 0.001], quaternion: [ 0, 0, -0.7071068, 0.7071068 ], inbound: "sg2"}
  - {type: "squadra_grande",  frame: "table", position: [ 0.061, 0.803, 0.001], quaternion: [ 0, 0, -0.7071068, 0.7071068 ], inbound: "sg3"}
  - {type: "squadra_grande",  frame: "table", position: [ 0.061, 0.930, 0.001], quaternion: [ 0, 0, -0.7071068, 0.7071068 ], inbound: "sg4"}

#  - {type: "squadra_piccola",  frame: "table", position: [ -0.003, 1.005, 0.053], quaternion: [-0.019, 0.999, 0.036, -0.014], inbound: "desk1"}
#  - {type: "squadra_piccola",  frame: "table", position: [ 0.001, 1.078, 0.058], quaternion: [0.025, 0.998, 0.057, -0.023], inbound: "desk1"}
#  - {type: "squadra_piccola",  frame: "table", position: [0.004, 1.136, 0.053], quaternion: [-0.009, 0.998, 0.060, -0.021], inbound: "desk1"}
#  - {type: "squadra_piccola",  frame: "table", position: [ 0.008, 1.208, 0.059], quaternion: [-0.043, 0.997, 0.028, -0.051], inbound: "desk1"}
#  - {type: "squadra_piccola",  frame: "table", position: [ 0.003, 1.268, 0.051], quaternion: [0.021, 0.997, 0.072, -0.036], inbound: "desk1"}

#  - {type: "squadra_grande",  frame: "table", position: [ 0.045, 0.529, 0.054], quaternion: [0.739, 0.672, -0.033, -0.033], inbound: "desk2"}
#  - {type: "squadra_grande",  frame: "table", position: [ 0.056, 0.673, 0.052], quaternion: [0.690, 0.719, 0.051, 0.067], inbound:   "desk2"}
#  - {type: "squadra_grande",  frame: "table", position: [ 0.050, 0.803, 0.060], quaternion: [0.679, 0.734, 0.005, 0.028], inbound:   "desk2"}
#  - {type: "squadra_grande",  frame: "table", position: [ 0.054, 0.930, 0.058], quaternion: [0.677, 0.735, 0.001, -0.036], inbound:  "desk2"}
