inbound:
  boxes:
  - {name: "sp1",            frame: "table",        position: [ 0.004, 1.005, 0.053],  quaternion: [1.000, 0.000, 0.000, 0.000], height: 0.05 } # vettore
  - {name: "sp2",            frame: "table",        position: [ 0.004, 1.078, 0.053],  quaternion: [1.000, 0.000, 0.000, 0.000], height: 0.05 } # vettore
  - {name: "sp3",            frame: "table",        position: [ 0.004, 1.136, 0.053],  quaternion: [1.000, 0.000, 0.000, 0.000], height: 0.05 } # vettore
  - {name: "sp4",            frame: "table",        position: [ 0.004, 1.208, 0.053],  quaternion: [1.000, 0.000, 0.000, 0.000], height: 0.05 } # vettore
  - {name: "sp5",            frame: "table",        position: [ 0.004, 1.268, 0.053],  quaternion: [1.000, 0.000, 0.000, 0.000], height: 0.05 } # vettore
  - {name: "sg1",            frame: "table",        position: [ 0.045, 0.529, 0.054], quaternion: [0.7071068, -0.7071068, -0.000, -0.000], height: 0.05} # vettore
  - {name: "sg2",            frame: "table",        position: [ 0.045, 0.673, 0.054], quaternion: [0.7071068, -0.7071068, -0.000, -0.000], height: 0.05} # vettore
  - {name: "sg3",            frame: "table",        position: [ 0.045, 0.803, 0.054], quaternion: [0.7071068, -0.7071068, -0.000, -0.000], height: 0.05} # vettore  
  - {name: "sg4",            frame: "table",        position: [ 0.045, 0.930, 0.054], quaternion: [0.7071068, -0.7071068, -0.000, -0.000], height: 0.05} # vettore
  #- {name: "warehouse1",     frame: "table",        position: [-0.234, 0.408, 0.064], quaternion: [0.705, 0.708, 0.016, -0.031], height: 0.12} # vettore


inbound_pick_server:

  ik_sol_number: 512
  
  groups:
    manipulator: open_tip

  manipulator:
    #preferred_configuration: [1.248980837684973, -1.2228279109171156, 1.9792593061627755, -2.2428737618677026, 1.553286774142281, 3.2935401617108626]
    preferred_configuration: [1.4762239456176758, -1.7016049824156703, 1.7525199095355433, -0.6964729589274903, 1.4800915718078613, -2.1354430357562464]
    
    preferred_configuration_weight: [0, 1, 1, 1, 1, 1]
    max_ik_goal_number: 512
    use_single_goal: false

  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints
