cube:
  color: [1,0.8,0,1.]
  box:  [0.05,0.05,0.05]

  offset: [0,0,0.025] #
  grasp_poses:
  - {tool: "open_tip", position: [0, 0, 0.010], quaternion: [0,0,0,1]}
  - {tool: "open_tip", position: [0, 0, 0.010], quaternion: [0,0,1,0]}
  - {tool: "open_tip", position: [0, 0, 0.010], quaternion: [ 0, 0, 0.7071068, 0.7071068 ]}
  - {tool: "open_tip", position: [0, 0, 0.010], quaternion: [ 0, 0, -0.7071068, 0.7071068 ]}


pin:
  color: [1,0.8,0,0.8]
  mesh: "package://sharework_cembre_skills/mesh/pin_9_5_mm_smusso.STL"
  scale: [0.001, 0.001, 0.001]

  offset_quaternion: [ 0.5, 0.5, 0.5, 0.5 ]
  offset: [0,0,0] #
  grasp_poses:
  - {tool: "open_tip", position: [0, 0, 0.005], quaternion: [1,0,0,0]}


squadra_grande:
  color: [1,0.8,0,1.]
  mesh: "package://sharework_cembre_description/mesh/squadra120mm.STL"
  scale: [0.001, 0.001, 0.001]

  offset: [0,0,0.00] #
  grasp_poses:
  - {tool: "open_tip", position: [0, 0, 0.060], quaternion: [1,0,0,0]}
  - {tool: "open_tip", position: [0, 0, 0.060], quaternion: [0,1,0,0]}

squadra_piccola:
  color: [1,0.8,0,1.]
  box:  [0.08,0.04,0.08]
  mesh: "package://sharework_cembre_description/mesh/squadra40mm.STL"
  scale: [0.001, 0.001, 0.001]

  offset: [0,0,0.00] #
  grasp_poses:
  - {tool: "open_tip", position: [0, 0, 0.060], quaternion: [1,0,0,0]}
  - {tool: "open_tip", position: [0, 0, 0.060], quaternion: [0,1,0,0]}


