outbound_mosaic:
  frame: "table"
  groups:
    manipulator: open_tip
  finite_slot: false
  slots:
  - {name: "A1", position: [0.490, 0.408, 0.26], quaternion: [0.7071068, -0.7071068, 0.000, 0.000],  approach_distance: [0, 0, 0.020]}
  - {name: "A2", position: [0.490, 0.408, 0.26], quaternion: [1,0,0,0],                              approach_distance: [0, 0, 0.020]}
  - {name: "A3", position: [0.490, 0.408, 0.26], quaternion: [0.7071068,  0.7071068, 0.000, 0.000],  approach_distance: [0, 0, 0.020]}
  - {name: "B1", position: [0.490, 1.040, 0.26], quaternion: [1,0,0,0],                              approach_distance: [0, 0, 0.020]}
  - {name: "B2", position: [0.490, 1.040, 0.26], quaternion: [0.7071068, -0.7071068, 0.000, 0.000],  approach_distance: [0, 0, 0.020]}
  - {name: "B3", position: [0.490, 1.040, 0.26], quaternion: [0.7071068,  0.7071068, 0.000, 0.000],  approach_distance: [0, 0, 0.020]}

  manipulator:
    max_ik_goal_number: 120

# 11.5, 30, 19

  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints




