robot:
  group_name: "manipulator"
  recipe:
  - {action: "pick",  description: ["squadra_grande","squadra_piccola"]}
  - {action: "place", description: ["B1","B2","B3","A1","A2","A3"]}
  - {action: "pick",  description: ["squadra_grande","squadra_piccola"]}
  - {action: "place", description: ["B1","B2","B3","A1","A2","A3"]}
  - {action: "pick",  description: ["squadra_grande","squadra_piccola"]}
  - {action: "place", description: ["B1","B2","B3","A1","A2","A3"]}
  - {action: "pick",  description: ["squadra_grande","squadra_piccola"]}
  - {action: "place", description: ["B1","B2","B3","A1","A2","A3"]}
  - {action: "pick",  description: ["squadra_grande","squadra_piccola"]}
  - {action: "place", description: ["B1","B2","B3","A1","A2","A3"]}
  - {action: "pick",  description: ["squadra_grande","squadra_piccola"]}
  - {action: "place", description: ["B1","B2","B3","A1","A2","A3"]}


# ["B1","B2","B3","A1","A2","A3"]
# ["A2","B1"]
