human:
  group_name: "human_right_arm"
  recipe:
    J1: "blue_box"
    J2: "blue_box"
    J3: "blue_box"
    J4: "white_box"
    J5: "white_box"
    I1: "blue_box"
    I2: "blue_box"
    I3: "blue_box"
    I4: "white_box"
    I5: "white_box"
    H1: "blue_box"
    H2: "blue_box"
    H3: "blue_box"
    H4: "white_box"
    H5: "white_box"
    G1: "blue_box"
    G2: "blue_box"
    G3: "blue_box"
    G4: "white_box"
    G5: "white_box"
    F1: "blue_box"
    F2: "blue_box"
    F3: "blue_box"
    F4: "white_box"
    F5: "white_box"
    E1: "blue_box"
    E2: "blue_box"
    E3: "blue_box"
    E4: "white_box"
    E5: "white_box"
robot:
  group_name: "ur5_on_guide"
  recipe:
    A1: "orange_box"
    A2: "blue_box"
    A3: "blue_box"
    A4: "orange_box"
    A5: "blue_box"
    B1: "orange_box"
    B2: "blue_box"
    B3: "blue_box"
    B4: "orange_box"
    B5: "blue_box"
    C1: "orange_box"
    C2: "blue_box"
    C3: "blue_box"
    C4: "orange_box"
    C5: "blue_box"
    D1: "orange_box"
    D2: "blue_box"
    D3: "blue_box"
    D4: "orange_box"
    D5: "blue_box"


