scene_objects:
- {type: "box_grigio", frame: "table", position: [0.63, 0.956, 0.125], quaternion: [0, 0, 0, 1]}
- {type: "box_grigio", frame: "table", position: [0.63, 0.400, 0.125], quaternion: [0, 0, 0, 1]}

box_grigio:
  color: [0.2,0.2,0.2, 1.]
  box:  [0.19,0.30,0.12]
  offset_quaternion: [ 0, 0, 0, 1 ]
  offset: [0, 0, -0.06]


