dictitems:
  angle_x_lb: -3.14
  angle_x_ub: 3.14
  angle_xy_lb: 0.0
  angle_xy_ub: 0.5
  angle_y_lb: -3.14
  angle_y_ub: 3.14
  cluster_max_size: 4000
  cluster_min_size: 10
  confidence_lb: 10000.0
  confidence_ub: 10000000000.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      angle_x_lb: -3.14
      angle_x_ub: 3.14
      angle_xy_lb: 0.0
      angle_xy_ub: 0.5
      angle_y_lb: -3.14
      angle_y_ub: 3.14
      cluster_max_size: 4000
      cluster_min_size: 10
      confidence_lb: 10000.0
      confidence_ub: 10000000000.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      intensity_lb: 0.0
      intensity_ub: 10000000000.0
      name: Default
      octree_grid_resolution: 0.25
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
      voxel_grid_resolution: 0.25
      x_lb: -5.0
      x_ub: 5.0
      y_lb: -5.0
      y_ub: 5.0
      z_lb: 0.0
      z_ub: 3.0
    state: []
  intensity_lb: 0.0
  intensity_ub: 10000000000.0
  octree_grid_resolution: 0.25
  voxel_grid_resolution: 0.25
  x_lb: -5.0
  x_ub: 5.0
  y_lb: -5.0
  y_ub: 5.0
  z_lb: 0.0
  z_ub: 3.0
state: []
