group_names_map:
  mg: manipulator
  

mg:
  type: Multigoal
  max_distance: 0.2
  max_refine_time: 20.0
  extend: false
  local_bias: 0.25
  tube_radius: 0.02
  use_avoidance: false
  base_frame: world
  tool_frame: open_tip
  min_distance: 0.4
  max_distance: 0.6
  max_penalty: 10.0
  display_bubbles: true
  links:
  - open_tip
  - tool0
  - wrist_1_link
  - wrist_2_link
  - wrist_3_link
#  - forearm_link
#  - upper_arm_link

