group_names_map:
  mg1:                           manipulator
  # timebased:                     manipulator

default_planner_config: mg1

mg1:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 2.0
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.01


timebased:
  type: TimeBasedMultigoal
  max_distance: 0.2
  max_refine_time: 1500.0
  extend: false
  local_bias: 0.0
  tube_radius: 0.02
