group_names_map:
  dgaco: manipulator
  

dgaco:
  type: dgaco
  max_time: 10.0
  tree_max_time: 0.8
  tree_stall_generation: 1
  ants_number: 200
  number_of_nodes: 100
  ants_stall_generation: 10
  refinement: true
  tool_frame: open_tip
  occupancy_weight: 10000

