# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_joint:
    min_position: -3.142
    max_position:  3.142
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 3
  shoulder_lift_joint:
    min_position: -3.142
    max_position:  3.142
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 3
  shoulder_pan_joint:
    min_position: -3.142
    max_position:  3.142
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 3
  wrist_1_joint:
    min_position: -6.285
    max_position:  6.285
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 3
  wrist_2_joint:
    min_position: -6.285
    max_position:  6.285
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 3
  wrist_3_joint:
    min_position: -3.285
    max_position:  3.285
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 3
