# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  shoulder_pan_joint:
    has_velocity_limits: true
    max_position: 2.61799
    min_position: -2.61799
    # max_velocity: 2.09439510239
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    # max_acceleration: 5.0
    max_acceleration: 12.7
  shoulder_lift_joint:
    has_velocity_limits: true
    max_position: -0.122173
    min_position: -2.26893
    # max_velocity: 2.09439510239
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    # max_acceleration: 5.0
    max_acceleration: 12.7
  elbow_joint:
    has_velocity_limits: true
    max_position: 2.75
    min_position: -2.75
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    # max_acceleration: 5.0
    max_acceleration: 12.7
  wrist_1_joint:
    has_velocity_limits: true
    #max_position: 2.75
    #min_position: -2.75
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    # max_acceleration: 5.0
    max_acceleration: 12.7
  wrist_2_joint:
    has_velocity_limits: true
    #max_position: 2.75
    #min_position: -2.75
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    # max_acceleration: 5.0
    max_acceleration: 12.7
  wrist_3_joint:
    has_velocity_limits: true
    # max_position: 5.58505
    # min_position: -5.58505
    #max_position: 5.58505
    #min_position: -5.58505
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    # max_acceleration: 5.0
    max_acceleration: 12.7
