control_configurations:
- name: "watch"
  components:
  - {hardware_interface: "ur10e_hw",   controller: "js_pub", description: ""}
  - {hardware_interface: "planner_hw", controller: "js_pub", description: ""}
#  - {hardware_interface: "ur10e_hw", controller: "force_torque_sensor_controller", description: ""}
- name: "ctrl"
  depends: ["watch"]
  components:
  - {hardware_interface: "ur10e_hw", controller: "ctrl1", description: ""}
- name: "trajectory_tracking"
  depends: ["ctrl"]
  components:
  - {hardware_interface: "planner_hw", controller: "microinterpolator", description: ""}
