control_configurations:
- name: "warmup1"
  components:
  - {hardware_interface: "ur10e_hw", controller: "js_pub", description: ""}
- name: "feedforward"
  components:
  - {hardware_interface: "ur10e_hw", controller: "js_pub", description: ""}
  - {hardware_interface: "ur10e_hw", controller: "ctrl1", description: ""}
  - {hardware_interface: "ur10e_hw", controller: "ctrl2", description: ""}
  - {hardware_interface: "ur10e_hw", controller: "ctrl3", description: ""}
  - {hardware_interface: "ur10e_hw", controller: "ctrl4", description: ""}
  - {hardware_interface: "ur10e_hw", controller: "ctrl5", description: ""}
  - {hardware_interface: "ur10e_hw", controller: "ctrl6", description: ""}
- name: "trj_tracker"
  depends: "feedforward"
  components:
  - {hardware_interface: "planner_hw", controller: "thor_prefilter_planner", description: ""}
- name: "strip"
  depends: "feedforward"
  components:
  - {hardware_interface: "strip_hw", controller: "thor_prefilter_planner", description: ""}
- name: "joint_teleop"
  depends: "feedforward"
  components:
  - {hardware_interface: "planner_hw", controller: "joint_teleop", description: ""}
- name: "cart_teleop"
  depends: "feedforward"
  components:
  - {hardware_interface: "planner_hw", controller: "cart_teleop", description: ""}
- name: "manual_guidance"
  depends: "feedforward"
  components:
  - {hardware_interface: "planner_hw", controller: "manual_guidance", description: ""}

start_gazebo: false
gazebo_bringup_time: 0
configuration_dispatches:
  warmup1: 0.1
  feedforward: 4.0
  trj_tracker: 4.5
