ur10e_hw:
  type: "itia/control/FakeHwIfaceNodelet"
  joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  sampling_period: 0.002
  diagnostic_period: 0.1

  remap_source_args:
  - "/ur10e_hw/js_pub/joint_states"

  remap_target_args:
  - "/manipulator/joint_states"

  initial_position: [1.248980837684973, -1.2228279109171156, 1.9792593061627755, -2.2428737618677026, 1.553286774142281, 3.2935401617108626]
  #initial_position: [-1.5213110583236655, -1.7692155013630007, -1.5020878824021342, -1.4410855968246585, -1.5707963269999998, -0.0494852686763343]

  js_pub:
    type:         ros/control/JointStatePublisher
    controlled_joint:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint


  ctrl1:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "shoulder_pan_joint"

  ctrl2:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "shoulder_lift_joint"

  ctrl3:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "elbow_joint"

  ctrl4:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "wrist_1_joint"

  ctrl5:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "wrist_2_joint"

  ctrl6:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "wrist_3_joint"
