ssm:
  override_increase_speed: 10 # [%/s]
  override_decrease_speed: 100 # [%/s]
  areas:
  - name: "area0"
    override: 0
    corners:
    - [0.0, -1]
    - [1.2, -1]
    - [1.2,  1]
    - [0.0,  1]
  - name: "area1"
    override: 30
    corners:
    - [1.20, -1]
    - [1.60, -1]
    - [1.60,  1]
    - [1.20,  1]
#  - name: "area2"
#    override: 100
#    corners:
#    - [0.6, -1]
#    - [0.8, -1]
#    - [0.8,  1]
#    - [0.8,  1]

