ssm:
  override_increase_speed: 10 # [%/s]
  override_decrease_speed: 100 # [%/s]
  areas:
  - name: "area0"
    override: 0
    corners:
    - [0.0, -1]
    - [0.65, -1]
    - [0.65,  1]
    - [0.0,  1]
  - name: "area1"
    override: 50
    corners:
    - [0.65, -1]
    - [0.90, -1]
    - [0.90,  1]
    - [0.65,  1]
#  - name: "area2"
#    override: 100
#    corners:
#    - [0.6, -1]
#    - [0.8, -1]
#    - [0.8,  1]
#    - [0.8,  1]

