start_log: true

binary_logger:
  num_worker_threads: 10
  # test_path: is the path where the binary file will be saved (if empty the destination directory will be '/home/user/.ros' )
  test_path: '/home/galois/.ros'

  test_name: "test_dentista"
  append_time: true  # if true add time

  # manager_name: name of the nodlet manager (need to be equal to the name in the launch file)
  manager_name: 'binary_logger'

  # list of nodelet (unrelated to binary_logger package) that the user do not want to stop
  unstoppable_nodelets: []

  # Type of the topic that need to be logged (supported JointState, Imu, PoseStamped, WrenchStamped, Float64MultiArray)
  topic_type:
  - 'JointState'
  - 'WrenchStamped'
  - 'Tf'

  JointState:
    # List of the topic to be acquired
    topic_names:
    - '/ur10/joint_states'

    # Acquisition time (to be specified for each topic)
    duration:
      - 1000 #[s]

    # Message decimation (to be specified for each topic)
    decimation:
      - 1

  WrenchStamped:
    # List of the topic to be acquired
    topic_names:
    - '/ur10/wrench'

    # Acquisition time (to be specified for each topic)
    duration:
      - 1000 #[s]

    # Message decimation (to be specified for each topic)
    decimation:
      - 1

  Tf:
    topic_names:
    - tool_log


    # Acquisition time (to be specified for each topic)
    duration:
      - 1000 #[s]

    # Message decimation (to be specified for each topic)
    decimation:
      - 1



tool_log:
  base_frame: world
  tool_frame: tool0
