planner_hw:
  remap_source_args:
  - "/planner_hw/js_pub/joint_states"
  - "/planner_hw/microinterpolator/follow_joint_trajectory/cancel"
  - "/planner_hw/microinterpolator/follow_joint_trajectory/feedback"
  - "/planner_hw/microinterpolator/follow_joint_trajectory/goal"
  - "/planner_hw/microinterpolator/follow_joint_trajectory/result"
  - "/planner_hw/microinterpolator/follow_joint_trajectory/status"
  - "/planner_hw/microinterpolator/unscaled_joint_target"

  - "/planner_hw/microinterpolator_impedance/follow_joint_trajectory/cancel"
  - "/planner_hw/microinterpolator_impedance/follow_joint_trajectory/feedback"
  - "/planner_hw/microinterpolator_impedance/follow_joint_trajectory/goal"
  - "/planner_hw/microinterpolator_impedance/follow_joint_trajectory/result"
  - "/planner_hw/microinterpolator_impedance/follow_joint_trajectory/status"
  - "/planner_hw/microinterpolator_impedance/unscaled_joint_target"

  - "/planner_hw/microinterpolator_elastoplastic/follow_joint_trajectory/cancel"
  - "/planner_hw/microinterpolator_elastoplastic/follow_joint_trajectory/feedback"
  - "/planner_hw/microinterpolator_elastoplastic/follow_joint_trajectory/goal"
  - "/planner_hw/microinterpolator_elastoplastic/follow_joint_trajectory/result"
  - "/planner_hw/microinterpolator_elastoplastic/follow_joint_trajectory/status"
  - "/planner_hw/microinterpolator_elastoplastic/unscaled_joint_target"

  - "/planner_hw/simple_touch/simple_touch/cancel"
  - "/planner_hw/simple_touch/simple_touch/feedback"
  - "/planner_hw/simple_touch/simple_touch/goal"
  - "/planner_hw/simple_touch/simple_touch/result"
  - "/planner_hw/simple_touch/simple_touch/status"


  remap_target_args:
  - "/joint_states"
  - "/manipulator/follow_joint_trajectory/cancel"
  - "/manipulator/follow_joint_trajectory/feedback"
  - "/manipulator/follow_joint_trajectory/goal"
  - "/manipulator/follow_joint_trajectory/result"
  - "/manipulator/follow_joint_trajectory/status"
  - "/unscaled_joint_target"

  - "/manipulator/follow_joint_trajectory/cancel"
  - "/manipulator/follow_joint_trajectory/feedback"
  - "/manipulator/follow_joint_trajectory/goal"
  - "/manipulator/follow_joint_trajectory/result"
  - "/manipulator/follow_joint_trajectory/status"
  - "/unscaled_joint_target"

  - "/manipulator/follow_joint_trajectory/cancel"
  - "/manipulator/follow_joint_trajectory/feedback"
  - "/manipulator/follow_joint_trajectory/goal"
  - "/manipulator/follow_joint_trajectory/result"
  - "/manipulator/follow_joint_trajectory/status"
  - "/unscaled_joint_target"

  - "/simple_touch/cancel"
  - "/simple_touch/feedback"
  - "/simple_touch/goal"
  - "/simple_touch/result"
  - "/simple_touch/status"

  js_pub:
    # type:         ros/control/JointStatePublisher
    type:         cnr/control/JointStatePublisher
    controlled_joint: all
    base_link: "world"
    tool_link: "tool0"
    robot_description_param: /robot_description
    robot_description_planning_param: /robot_description_planning

  microinterpolator:
    type: "cnr/control/ScaledFJTPosController"
    controlled_joints: all
    continuity_order: 1

  microinterpolator_impedance:  # we need it to restart the planner when we switch to and from the impedance mode
    type: "cnr/control/ScaledFJTPosController"
    controlled_joints: all
    continuity_order: 1

  microinterpolator_elastoplastic:  # we need it to restart the planner when we switch to and from the impedance mode
    type: "cnr/control/ScaledFJTPosController"
    controlled_joints: all
    continuity_order: 1


  simple_touch:
    type: cnr/control/SimpleTouchController
    sensor_name : "wrench"
    base_link   : "world"
    tool_link   : "tool0"
    sensor_frame: "tool0"
    output_twist_ns: "/target_cart_twist"

  cartesian_velocity:
    appenders: [file, screen]
    levels: [trace, info]
    pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
    file_name: "cartesian_velocity_planner"

    type: cnr/control/CartesianVelocityController
    controlled_joints : all
    kin_update_period : 0.002
    target_twist_topic: /target_cart_twist  # setpoint twist topic name

  cartesian_velocity:
    appenders: [file, screen]
    levels: [trace, info]
    pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
    file_name: "cartesian_velocity"

    type: cnr/control/CartesianVelocityController
    controlled_joints : all
    kin_update_period : 0.002
    target_twist_topic: /target_cart_twist  # setpoint twist topic name
