planner_hw:
  type: "itia/control/TopicHwIfaceNodelet"
  joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint
  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic: "/manipulator/joint_states"
  command_joint_state_topic:  "/manipulator/joint_target"
  sampling_period: 0.002
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20

  remap_source_args:
  - "/planner_hw/thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/planner_hw/thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/planner_hw/thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/planner_hw/thor_prefilter_planner/follow_joint_trajectory/result"
  - "/planner_hw/thor_prefilter_planner/follow_joint_trajectory/status"

  remap_target_args:
  - "/manipulator/follow_joint_trajectory/cancel"
  - "/manipulator/follow_joint_trajectory/feedback"
  - "/manipulator/follow_joint_trajectory/goal"
  - "/manipulator/follow_joint_trajectory/result"
  - "/manipulator/follow_joint_trajectory/status"

  thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    spline_order: 1



  joint_teleop:
    type: "itia/control/JointTeleopController"
    setpoint_topic_name: "/manipulator/target_joint_state"
    controlled_joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

  cart_teleop:
    type: "itia/control/CartTeleopController"
    setpoint_topic_name: "/manipulator/target_twisted_stamped"
    base_link: "world"
    tool_link: "tool0"
    controlled_joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
