planner_ethernet_hw:
  remap_source_args:
  - "/planner_ethernet_hw/js_pub/joint_states"

  remap_target_args:
  - "/joint_states"

  js_pub:
    # type:         ros/control/JointStatePublisher
    type:         cnr/control/JointStatePublisher
    controlled_joint: all
    base_link: "world"
    tool_link: "tool0"
    robot_description_param: /robot_description
    robot_description_planning_param: /robot_description_planning

  cartesian_velocity:
    appenders: [file, screen]
    levels: [trace, info]
    pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
    file_name: "cartesian_velocity"

    type: cnr/control/CartVelocityController
    controlled_joints : all
    kin_update_period : 0.002
    target_twist_topic: /target_cart_twist  # setpoint twist topic name
