planner_hw:
  type           : "cnr/control/TopicsRobotHW"
  appenders      : [file, screen]
  levels         : [trace, info]
  pattern_layout : "[%5p][%d{HH:mm:ss,SSS}][%50M:%04L][%24c] %m%n"
  file_name      : "planner_hw"

  resources: [ joint_resource ]
  joint_resource:
    joint_names:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    subscribed_topics :
    - /ur10/joint_states
    - /ur10/joint_states
    - /ur10/joint_states
    - /ur10/joint_states
    - /ur10/joint_states
    - /ur10/joint_states
    published_topics :
    - /joint_target

  sampling_period: 0.002
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20
  maximum_missing_cycles: 1000
  base_link: world
  tool_link: tool0
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
