strip_hw:
  type: "itia/control/TopicHwIfaceNodelet"
  joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint
  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic: "/manipulator/joint_states"
  command_joint_state_topic:  "/strip/joint_target"
  sampling_period: 0.002
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20

  remap_source_args:
  - "/strip_hw/thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/strip_hw/thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/strip_hw/thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/strip_hw/thor_prefilter_planner/follow_joint_trajectory/result"
  - "/strip_hw/thor_prefilter_planner/follow_joint_trajectory/status"
  - "/strip_hw/thor_prefilter_planner/execution_ratio"

  remap_target_args:
  - "/manipulator/follow_joint_trajectory/cancel"
  - "/manipulator/follow_joint_trajectory/feedback"
  - "/manipulator/follow_joint_trajectory/goal"
  - "/manipulator/follow_joint_trajectory/result"
  - "/manipulator/follow_joint_trajectory/status"
  - "/execution_ratio"

  thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    spline_order: 1


