touch_hw:
  type          : "itia/control/TopicsHwIfaceNodelet"
  debug: false
  resources     : [ wrench_resource ]
  maximum_missing_messages    : 10000

  wrench_resource:
    sensor_name      : tool0
    frame_id         : tool0
    subscribed_topics : ["/ur10e_hw/wrench"]



  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic: "/manipulator/joint_states"
  command_joint_state_topic:  "/manipulator/joint_target"
  sampling_period: 0.002
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20

  force_torque_sensor_controller:
    type: force_torque_sensor_controller/ForceTorqueSensorController
    publish_rate: 500
  touch:
    type              : "itia/control/SimpleTouchController"
    debug: true
    cycle_time        : 0.002
    leaving_time      : 0.0
    sensor_name       : "tool0"
    sensor_frame      : "tool0"
    base_link         : "world"
    tool_link         : "open_tip"
    action_ns         : "/geodetic_cartesian_planner"
    output_twist_ns   : "/planner_hw/cart_teleop/target_cart_teleop"
