touch_hw:
  type: "itia/control/TopicHwIfaceNodelet"
  joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint
  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic: "/manipulator/joint_states"
  command_joint_state_topic:  "/manipulator/joint_target"
  sampling_period: 0.002
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20

#  remap_source_args:

#  remap_target_args:

  touch:
    type: itia/control/SimpleTouchController
    base_link: world
    tool_link: open_tip
    sensor_frame: tool0
    output_twist_ns: "/planner_hw/cart_teleop/target_cart_teleop"
