ur10e_hw:
  type: cnr_ur_driver/UrCB3HardwareInterface
  appenders: [file, screen]
  levels: [debug, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
  file_name: "ur10e_hw"
  default_throttle_time: 20.0
  sampling_period: 0.002
  joints:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  wrench_frame_id: wrench

  robot_ip: "192.168.20.2"
  reverse_port: 50001
  script_sender_port: 50002
  tf_prefix: ''
  headless_mode: false
  use_tool_communication: true
  tool_voltage: 24
  tool_parity: 0
  tool_baud_rate: 115200
  tool_stop_bits: 1
  tool_rx_idle_chars: 1.5
  tool_tx_idle_chars: 3.5
  ext_control_path: /programs/exc.urp
  tool_device_name: /home/galois/.ros/ttyUR  # remember that your user needs to have the rights to write that file handle
  max_tracking_error: 1.0

  base_link  : "world"
  tool_link  : "tool0"
  kin_update_period: 0.002
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
  dashboard:
    receive_timeout: 3.0
