ur10e_hw:
  remap_source_args:
  - "/ur10e_hw/js_pub/joint_states"
  - "/ur10e_hw/microinterpolator/follow_joint_trajectory/cancel"
  - "/ur10e_hw/microinterpolator/follow_joint_trajectory/feedback"
  - "/ur10e_hw/microinterpolator/follow_joint_trajectory/goal"
  - "/ur10e_hw/microinterpolator/follow_joint_trajectory/result"
  - "/ur10e_hw/microinterpolator/follow_joint_trajectory/status"
  - "/ur10e_hw/microinterpolator/unscaled_joint_target/joint_states"

  remap_target_args:
  - "/ur10/joint_states"
  - "/manipulator/follow_joint_trajectory/cancel"
  - "/manipulator/follow_joint_trajectory/feedback"
  - "/manipulator/follow_joint_trajectory/goal"
  - "/manipulator/follow_joint_trajectory/result"
  - "/manipulator/follow_joint_trajectory/status"
  - "/unscaled_joint_target"


  force_torque_sensor_controller:
     type:         force_torque_sensor_controller/ForceTorqueSensorController
     publish_rate: 500

  js_pub:
    appenders: [file, screen]
    levels: [trace, info]
    pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
    file_name: "ur10e_hw_js_pub"

    type:         cnr/control/JointStatePublisher
    controlled_joint: all
    base_link: "world"
    tool_link: "tool0"
    robot_description_param: /robot_description
    robot_description_planning_param: /robot_description_planning


  ctrl1:
    type:        cnr/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_target"
    controlled_joint: all
    enable_setpoint_watchdog: false

  microinterpolator:
    type: "cnr/control/ScaledFJTPosController"
    controlled_joints: all
    continuity_order: 1
