ur10e_hw:
  type: cnr_ur_driver/UrCB3HardwareInterface
  appenders: [file, screen]
  levels: [trace, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
  file_name: "ur10e_hw"
  default_throttle_time: 20.0
  sampling_period: 0.002
  joints:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  robot_ip: "192.168.10.1"
  reverse_port: 50001
  script_sender_port: 50002
  tf_prefix: ''
  headless_mode: false
  use_tool_communication: false
  tool_voltage: 0
  tool_parity: 0
  tool_baud_rate: 115200
  tool_stop_bits: 1
  tool_rx_idle_chars: 1.5
  tool_tx_idle_chars: 3.5
  ext_control_path: /programs/exc.urp

  base_link  : "world"
  tool_link  : "tool0"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
