ur10e_hw:
  type: urCB3_driver/HardwareInterface #cnr_ur_driver/UrCB3HardwareInterface
  appenders: [file, screen]
  levels: [info, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
  file_name: "ur_hw"
  default_throttle_time: 20.0
  sampling_period: 0.008
  joints:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  robot_ip: "192.168.10.1"
  reverse_port: 50001
  script_sender_port: 50002
  tf_prefix: ''
  headless_mode: false
  script_file: /home/brontolo/community_ws/src/devices/robots/Universal_Robots_ROS_Driver/ur_robot_driver/resources/ros_control.urscript
  output_recipe_file: /home/brontolo/community_ws/src/devices/robots/Universal_Robots_ROS_Driver/ur_robot_driver/resources/rtde_output_recipe.txt
  input_recipe_file: /home/brontolo/community_ws/src/devices/robots/Universal_Robots_ROS_Driver/ur_robot_driver/resources/rtde_input_recipe.txt
  ext_control_path: /programs/exc.urp
  use_tool_communication: false
  tool_voltage: 0
  tool_parity: 0
  tool_baud_rate: 115200
  tool_stop_bits: 1
  tool_rx_idle_chars: 1.5
  tool_tx_idle_chars: 3.5

  base_link  : "base_link"
  tool_link  : "tool0_link"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
